name: 'wealth_edit_overlay_sample'
version: '1.0'
config-version: 2

profile: 'wealth_edit_profile'

model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']

models:
  wealth_edit_overlay_sample:
    staging:
      materialized: view
    intermediate:
      materialized: view
    overlay:
      materialized: table